---
- hosts: localhost
  tasks:
 - name: create s3 bucket
   s3_bucket:
     name: my-ansible-bucket
     state: present
     region:
     versioning: yes
     tags:
       name: my-ansible-bucket
       type: example
     
 
  
